services:
  broker-rabbitmq:
    image: rabbitmq:3-management
    container_name: broker-rabbitmq
    ports:
      - "11883:1883" 
      - "5673:5672"
      - "15672:15672"
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_mqtt && 
               rabbitmq-plugins enable rabbitmq_management && 
               rabbitmq-server"
    networks:
      - red-distribuidos
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  servicio-expedientes:
    build: ./Servicio_Expendientes
    container_name: servicio-expedientes
    environment:
      - QUARKUS_HTTP_PORT=8081
    networks:
      - red-distribuidos

  proxy:
    image: nginx:alpine
    container_name: balanceador-nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - servicio-expedientes
    networks:
      - red-distribuidos

  servicio-permisos:
    build: ./Servicio_Permisos
    container_name: servicio-permisos
    ports:
      - "9090:9090"
      - "8080:8080"
    depends_on:
      - servicio-expedientes
    networks:
      - red-distribuidos

  servicio-autenticacion:
    build: ./Servicio_Autenticacion
    container_name: servicio-autenticacion
    depends_on:
      broker-rabbitmq:
        condition: service_healthy
      servicio-permisos:
        condition: service_started
    networks:
      - red-distribuidos

  sensor-biometrico:
    build: ./Sensor_Biometrico
    container_name: sensor-biometrico
    # Esperamos a que los servidores estén listos
    entrypoint: bash -c "sleep 15 && java -cp app.jar:lib/* com.sensor_biometrico.Sensor_Biometrico"
    depends_on:
      broker-rabbitmq:
        condition: service_healthy
      servicio-autenticacion:
        condition: service_started
    networks:
      - red-distribuidos

  app-paciente:
    build: ./App_Paciente
    container_name: app-paciente
    depends_on:
      - servicio-permisos
    networks:
      - red-distribuidos

  sistema-hospital:
    build: ./Sistema_Hospital
    container_name: sistema-hospital
    # Esperamos lo suficiente para que la huella se procese y el paciente apruebe (auto)
    entrypoint: bash -c "sleep 30 && java -cp app.jar:lib/* com.sistema_hospital.Sistema_Hospital"
    depends_on:
      - servicio-expedientes
      - app-paciente
    networks:
      - red-distribuidos

networks:
  red-distribuidos:
    driver: bridge
