worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Pool de servidores Quarkus (Round Robin Ponderado)
    # Mandará 3 peticiones a la Instancia 1 por cada 1 que mande a la Instancia 2
    upstream servicio_expediente {
        server localhost:8081 weight=3; # Tu instancia actual (HTTP Quarkus)
        server localhost:8082 weight=1; # Tu segunda instancia clonada
    }

    server {
        listen       80;
        server_name  localhost;

        # Archivos de logs para monitorear el balanceo de carga
        access_log logs/balanceador_access.log;
        error_log logs/balanceador_error.log;

        # Captura todo el tráfico que entra al puerto 80 y lo redirige a Quarkus
        location / {
            proxy_pass http://servicio_expediente;
            
            # Cabeceras HTTP para transferir la IP y protocolo real del cliente
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Manejo de errores en caso de que las instancias de Quarkus estén apagadas
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}